import os

AZURE_OPENAI_RESOURCE = os.environ.get('AZURE_OPENAI_RESOURCE', 'oai0-yohpwy4qqbu36')
AZURE_OPENAI_CHATGPT_DEPLOYMENT = os.environ.get('AZURE_OPENAI_CHATGPT_DEPLOYMENT', 'chat')
AZURE_OPENAI_API_VERSION = os.environ.get('AZURE_OPENAI_API_VERSION', '2024-02-01')
MAX_ROUNDS = int(os.environ.get('AUTOGEN_MAX_ROUNDS', 10))
AZURE_OPENAI_KEY = os.environ.get('AZURE_OPENAI_KEY','')
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = "text-embedding-ada-002"